version: '3.4'
services:
  svelte:
    image: texfinder:latest
    container_name: textFinder
    restart: always
    build: .

    environment:
      - PORT=3000

      - TZ=Europe/Oslo

    ports:
      - 3000:3000
