name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "App_name=tesseractjs-svelte" >> "$GITHUB_ENV"
          else
              echo "App_name=tesseractjs-svelte-staging" >> "$GITHUB_ENV"
          fi
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: $App_name
          heroku_email: 'magnusaga@gmail.com'
