name: Playwright Tests
on:
  push:
    branches: [main, develop]
    paths:
      - './src/**/*'
      - './tests/**/*'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: build
        run: pnpm run build
      - name: Run Playwright tests
        run: npm run test:ci
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
